name: 'publish-wasm'
description: 'Publishes Wasm bindings to npm'
inputs:
  tag:
    description: 'Which npm tag to publish under e.g. `dev`, will default to `latest`'
    required: false
  npm-token:
    description: 'used for authenticating towards npm'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        check-latest: true

    - name: Install dependencies
      shell: sh
      working-directory: bindings/stronghold-nodejs
      run: npm ci --ignore-scripts --legacy-peer-deps

    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: bindings/stronghold-nodejs/artifacts

    - name: Create npm folder
      shell: sh
      working-directory: bindings/stronghold-nodejs
      run: npm run create-npm-dir

    - name: Move artifacts
      shell: sh
      working-directory: bindings/stronghold-nodejs
      run: npm run artifacts

    - name: List packages
      shell: sh
      working-directory: bindings/stronghold-nodejs
      run: ls -R ./npm

    - name: Publish
      shell: sh
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      # will publish 'latest' tag if no tag is passed
      run: echo npm publish $(if [ ${{ inputs.tag }} != '' ]; then echo --tag ${{ inputs.tag }}; fi) --access public
